brew 'git'
brew 'fish'
brew 'zoxide'
brew 'stow'
brew 'wget'
brew 'bat'
brew 'broot'
brew 'tree'
brew 'btop'
brew 'colima'
brew 'docker'
brew 'docker-compose'
brew 'docker-credential-helper'
brew 'eza'
brew 'gh'
brew 'gcc'
brew 'helix'
brew 'fzf'
brew 'neovim'
brew 'httpie'
brew 'gnupg'
brew 'jq'
brew 'lazygit'
brew 'lazydocker'
#brew 'lua'
#brew 'make'
brew 'mas'
brew 'fastfetch'
brew 'ripgrep'
brew 'rm-improved'
#brew 'rustup'
#brew 'pnpm'
brew 'mise'
brew 'uv'
# casks
cask 'ghostty'
cask 'vlc'
cask 'folx'
cask 'mullvadvpn'
cask 'zotero'
cask 'dbvisualizer'
cask 'obsidian'
cask 'maccy'
cask 'bitwarden'
cask 'hammerspoon'
cask 'raycast'
cask 'vesktop'
cask 'keka'

# mac app store 
mas "Tailscale", id: 1475387142
mas "Dropover - Easier Drag & Drop", id: 1355679052

# fonts
cask 'font-fira-code-nerd-font'
cask 'font-victor-mono-nerd-font'
cask 'font-sauce-code-pro-nerd-font'
cask 'font-iosevka-nerd-font'
cask 'font-jetbrains-mono-nerd-font'

